### ISSUE TITLE
[PW-7545] Incorrect validation of webhooks signature that contain special characters

### ISSUE THREAD

**Issue by nbermudezs** [Adyen/adyen-ruby-api-library#108]
**Describe the bug**
When using the HmacValidator on a webhook that contains special characters such as `/` or `:` the validation does NOT pass. Despite being valid and passing when using the Node.js SDK HmacValidator.

Specifically I started seeing issues cause by this with `REPORT_AVAILABLE` webhooks for reports manually generated. These webhooks include the full URL to the report under the `reason` attribute and is mistakenly being escaped by the Ruby SDK HmacValidator.

**How to reproduce**
1. Take the following webhook example:

```
{
  "NotificationRequestItem": {
    "additionalData": {
      "hmacSignature": "AuriseiMKi3w19nnZHVdktjqdubXyuhjUy86OHwF9tM="
    },
    "amount": {
      "currency": "EUR",
      "value": 0
    },
    "eventCode": "REPORT_AVAILABLE",
    "eventDate": "2022-11-01T21:10:57+01:00",
    "merchantAccountCode": "ACC_CODE",
    "merchantReference": "",
    "pspReference": "threedsecure_authentication_report_2022-11-01T00:00:00_2022-11-02T23:59:59.csv",
    "reason": "https://ca-live.adyen.com/reports/download/MerchantAccount/ACC_CODE/threedsecure_authentication_report_2022-11-01T00:00:00_2022-11-02T23:59:59.csv",
    "success": "true"
  }
}
```

2. Calculate the HMAC signature using the manual process described in [Adyen docs](https://docs.adyen.com/development-resources/webhooks/verify-hmac-signatures#verify-using-your-own-solution) and replace the `hmacSignature` in the webhook above with the calculated value

3. Attempt to validate it using `HmacValidator` and see the result is `false`

4. Attempt to validate it using the Node.js `HmacValidator` [here](https://github.com/Adyen/adyen-node-api-library/blob/develop/src/utils/hmacValidator.ts) and see the result is `true`

This is happening because the Node.js version does not escape the value because it goes through [here](https://github.com/Adyen/adyen-node-api-library/blob/develop/src/utils/hmacValidator.ts#L57) while the Ruby SDK _always_ escapes the value [here](https://github.com/Adyen/adyen-ruby-api-library/blob/develop/lib/adyen/utils/hmac_validator.rb#L26)

**Expected behavior**

`HmacValidator` should correctly handle `reason` payloads that contain special characters

**Screenshots**

**Desktop (please complete the following information):**
 - ruby Version: [x.y.z]
 - Library Version: [x.y.z]

**Additional context**

**Comment by michaelpaul** [comment]
Hello @nbermudezs, thanks for reporting this issue! We recorded it in our backlog and will soon pick it up.
