### ISSUE TITLE
JSON Parser error on deleting stored payment method

### ISSUE THREAD

**Issue by paulmccarthy42** [Adyen/adyen-ruby-api-library#133]
**Describe the bug**
When deleting a stored payment method using this library, it looks like the API call succeeds, but the library returns a JSON parsing error because the response is empty.

The issue is, it looks like it should be empty - the response in the test portal shows a 204 - so the library should at least expect a payload like this.

**How to reproduce**
1. Instantiate a gateway object
```gateway = Adyen::Client.new(env: 'test', api_key: '******')```
2. Use it to try and delete a known StoredPaymentMethod
```gateway.checkout.stored_payment_methods.delete("G94BB28TP6KXWD82", {shopperReference: "8527589", merchantAccount: "********"})```
3. You should get a JSON parsing error 
```JSON::ParserError: 767: unexpected token at '' from /Users/pmccarthy/.rbenv/versions/2.6.3/lib/ruby/2.6.0/json/common.rb:156:in 'parse'```
4. Go to https://ca-test.adyen.com/ to look at API logs, and confirm the request was received and returned a 204 status

**Expected behavior**
I would have expected an Adyen::AdyenResult object with status = 204 and response = nil or []

**Screenshots**

**Desktop (please complete the following information):**
 - ruby Version: [2.6.3]
 - Library Version: [6.30]

**Additional context**
Not clear on what the decorum is for posting account info here, but the log id from ca-test.adyen.com for the interaction above is `APIL42255223223D5HQ8HW455B6HBD`

**Comment by antolo-arch** [comment]
Hi @paulmccarthy42 

Thanks for brining that issue to out attention. I have made changes in the library which will solve the problem. 

Kind regards, 

Antoni
