### ISSUE TITLE
v7.0.0 Broken in Live

### ISSUE THREAD

**Issue by ollym** [Adyen/adyen-ruby-api-library#139]
```ruby
client = Adyen::Client.new
client.api_key = '...'
client.env = :live
client.live_url_prefix = 'abc123'

client.checkout.payments_api.payment_methods({ merchantAccount: 'Test' })
```

Will call:

`https://abc123-checkout-live.adyenpayments.com/v70/paymentMethods`

Instead of:

`https://abc123-checkout-live.adyenpayments.com/checkout/v70/paymentMethods`

It works in test, just breaks in live.

**Comment by ollym** [comment]
@jillingk @wboereboom quite a serious production issue if you can take a look

**Comment by ollym** [comment]
A temporary fix for anyone else struggling...

```ruby
# config/initializers/adyen.rb
module AdyenClientFixes
  def service_url_base(service)
    url = super
    url = "#{url}/checkout" if @env == :live && service == "Checkout"
    url
  end
end

Adyen::Client.prepend(AdyenClientFixes)
```

**Comment by wboereboom** [comment]
Hi @ollym ,

Thanks for bringing this one to our attention.
Hope our patch release resolves the issue for you.

Our apologies for any delay this might have caused.

Kind Regards,
Wouter
Adyen
