### ISSUE TITLE
"Required object 'amount' is not provided." - Got this error by hitting the refund()

### ISSUE THREAD

**Issue by viveknegi111** [Adyen/adyen-ruby-api-library#168]
**Describe the bug**
Got this error - response = { "status"=>422, "errorCode"=>"100", "message"=>"Required object 'amount' is not provided.",
   "errorType"=>"validation" }
 by hitting the AdyenClient.new.payments.refund(input1, input2)

**How to reproduce**
Steps to reproduce the behavior.
   a) initializing first:
   adyen_client = Adyen::Client.new.tap do |_adyen|
      _adyen.api_key = "some value"
      _adyen.env =  :live
      _adyen.live_url_prefix = "some value"
      _adyen.checkout.version = 68
    end
   b) By hitting this adyen_client.payments.refund(input1, input2) where

    input1 = {
      'amount': {
        'value': 456,
        'currency': "USD"
      },
      'reference': "some value1",
      'merchantAccount': "some value2"
    }

    input2 =   {"paymentPspReference": "some value3"}

    I got the above mentioned error. Please check . Is something missing here from my end in passing parameters?
    
**Expected behavior**
No idea about the response as hitting the API gives error.

**Screenshots**

<img width="1053" alt="Screenshot 2023-08-25 at 8 16 26 PM" src="https://github.com/Adyen/adyen-ruby-api-library/assets/100793069/23d4bf06-67d4-4f74-81c0-0993851171b5">

**Desktop (please complete the following information):**
 - ruby Version: [x.y.z] - 2.7.4
 - Library Version: [x.y.z] - gem 'adyen-ruby-api-library', '~> 6.2'

**Additional context**
None

**Comment by MuhammadIbtisam** [comment]
Hello @viveknegi111 please use "modificationAmount" in your input1 params instead of "amount".
Proper Request Format:
{
  "merchantAccount": "TestMerchant",
  "originalReference": "8123456789012345",
  "modificationAmount": {
    "value": 2000,
    "currency": "EUR"
  }
}

as format specified in the spec/mocks/requests/Payment/refund.json
