### ISSUE TITLE
NoMethodError:  undefined method `default_adapter_options' for Faraday:Module

### ISSUE THREAD

**Issue by jotolo** [Adyen/adyen-ruby-api-library#177]
**Describe the bug**
```
Failure/Error:
       Adyen::Client.new(api_key: credentials[:ADYEN_API_KEY],
                         env: credentials[:ADYEN_ENV],
                         live_url_prefix: adyen_live_url)
     
     NoMethodError:
       undefined method `default_adapter_options' for Faraday:Module
```

**How to reproduce**
If you try to initialize `Adyen::Client` class you will get this error

**Expected behavior**
Being able to initialize the `Adyen::Client` class

**Additional context**
It started with version 7.3.0 and it seems to be related to https://github.com/Adyen/adyen-ruby-api-library/pull/169 
When no `adapter_options` is specified, it triggers the before mentioned error

**Comment by ollym** [comment]
@jotolo it was added in Faraday v2.1.0 https://github.com/lostisland/faraday/releases/tag/v2.1.0

What version are you using? (`Faraday::VERSION`)

**Comment by jotolo** [comment]
Hi @ollym , we are using Faraday 1.10.3. This is why the issue is triggering but there is no constraint on the version needed by the library. Is it needed?

**Comment by jotolo** [comment]
@ollym Correct. The proposed solution works. I saw #178 was opened and it manages to solve the issue. Once that PR is merged we can close this issue. 
Thanks @ollym and @Aleffio for the quick response 🤝 .
