### ISSUE TITLE
Support for Authorise3DS2

### ISSUE THREAD

**Issue by x4d3** [Adyen/adyen-ruby-api-library#19]
Hello,

The current version of the gem does not appear to be supporting Authorise3DS2: https://docs.adyen.com/api-explorer/#/Payment/v40/authorise3ds2

Is it planned to add it to the gem ?

**Comment by crrood** [comment]
Hi,

Indeed, I've created a new pull request to add /authrorise3ds2 - https://github.com/Adyen/adyen-ruby-api-library/pull/20

Colin Rood
Adyen

**Comment by x4d3** [comment]
Thanks @crrood that was super duper quick !
