### ISSUE TITLE
Origin Key endpoint constructed incorrectly

### ISSUE THREAD

**Issue by ScottPowell14** [Adyen/adyen-ruby-api-library#29]
When constructing the /originKey service url, the endpoint structure is be:

https://[live-prefix]-checkout-live.adyenpayments.com/CheckoutUtility/v1/originKeys 
whereas it should be
https://[live-prefix]-checkout-live.adyenpayments.com/checkout/v1/originKeys 

Described here: https://docs.adyen.com/development-resources/live-endpoints#checkout-endpoints

This is where the service CheckoutUtility is used when constructing the url: https://github.com/Adyen/adyen-ruby-api-library/blob/develop/lib/adyen/client.rb#L64

**Comment by brenthoughton** [comment]
Submitted a PR here: https://github.com/Adyen/adyen-ruby-api-library/pull/33

**Comment by crrood** [comment]
Fixed by PR #36
