### ISSUE TITLE
Idempotency

### ISSUE THREAD

**Issue by nicklloyd** [Adyen/adyen-ruby-api-library#35]
Hi there,

We were hoping to take advantage of idempotency as described [here](https://docs.adyen.com/development-resources/api-idempotency) but I don't see anything in the Faraday connection that would handle setting the header.

As this would be on a request level, maybe it could be fetched from `request_data` before setting up the connection and set the header if present?

**Comment by crrood** [comment]
Hi Nick,

Thanks for bringing this up, idempotency would be good functionality to have.

I want to maintain the 1:1 relationship between the object passed in request_data and the request sent to the Adyen API, but we could add an optional "headers" parameter to the service method.

I've created a pull request https://github.com/Adyen/adyen-ruby-api-library/pull/37 which will be merged, pending review.
