### ISSUE TITLE
Alternative mock host name

### ISSUE THREAD

**Issue by gcmannb** [Adyen/adyen-ruby-api-library#41]
Hi,  I have a minor suggestion that would help us to use the client library in integration tests and our own environments.

What do you think of adding `mock_address` so that a name other than localhost can be used for the mock environment?  Maybe even `mock_service_url_base`?

e.g.
https://github.com/Adyen/adyen-ruby-api-library/blob/develop/lib/adyen/client.rb#L10

Happy to do this as a PR if this idea sounds reasonable.

Thanks,
Gary

**Comment by crrood** [comment]
Hi Gary,

Sure, seems like a good addition.  Go ahead and submit a PR.

Cheers,
Colin
