### ISSUE TITLE
Doesn't work in the :live mode

### ISSUE THREAD

**Issue by hafizio** [Adyen/adyen-ruby-api-library#6]
The library integration works well when I was testing it the `:test` mode, but once I updated my API credentials to the `:live` mode (https://ca-live.adyen.com), I keep getting this error:

```
Faraday::ConnectionFailed: Please confirm that Client.env is set to the right value (:live or :test)
```
I set up the Adyen::Client.env as `:live`. Is this an issue with the library or my account setup?

**Comment by hafizio** [comment]
This is what I was able to capture from out Sentry log:

```
Faraday::ConnectionFailed
Please confirm that Client.env is set to the right value (:live or :test)
SocketError
Failed to open TCP connection to checkout-live.adyen.com:443 (getaddrinfo: Name or service not known)
```

**Comment by hafizio** [comment]
I can also see that the endpoint should be different for the live endpoint:

```
[random]-[company name]-checkout-live.adyenpayments.com
```

Reference:
https://docs.adyen.com/developers/development-resources/live-endpoints#checkoutendpoints

**Comment by crrood** [comment]
Hi Hafizion,

Thanks for bringing this to our attention!  We've added a new variable Client.checkout_url_prefix which should be set to [random]-[company name].

For instance, if your full URL is https://9924a0f19cb1d71c-TestMerchant-checkout-live.adyenpayments.com/checkout/v32/paymentSession, Client.checkout_url_prefix will be 9924a0f19cb1d71c-TestMerchant.

It will be part of the pending 1.0.2 release.

Cheers,
Colin

**Comment by hafizio** [comment]
@crrood creating a payment session works now, but we still notice the wrong URL is being encoded in the checkout token:

```
{
    "checkoutshopperBaseUrl": "https:\/\/checkoutshopper-live.adyen.com\/checkoutshopper\/",
    "disableRecurringDetailUrl": "https:\/\/checkoutshopper-live.adyen.com\/checkoutshopper\/services\/PaymentInitiation\/v1\/disableRecurringDetail",
    "generationtime": "2018-10-01T07:42:06Z",
    "initiationUrl": "https:\/\/checkoutshopper-live.adyen.com\/checkoutshopper\/services\/PaymentInitiation\/v1\/initiate",
...
```

**Comment by crrood** [comment]
Hi Hafizio,

Can you give me a bit more information about where this object came from?  It is the response from the API?

**Comment by hafizio** [comment]
@crrood that's what we got from the `paymentSession` API result (the encoded result). That particular issue has been fixed, we're able to checkout using the `:live` option now, but it's now affecting our `:test` mode 😓

```
Faraday::ConnectionFailed: Please confirm that Client.env is set to the right value (:live or :test)
```

We're getting this error when testing on our `:test` mode while the `:live` option works.

**Comment by crrood** [comment]
Hi Hafizio,

Yes indeed, there was a bug in the fix for the checkout_url_prefix that broke it for the test environment.  It should be working on develop now.

For the URL in the API response, please just pass the encoded paymentSession object to the SDK as is.  It's not meant to be decoded or edited in any way.
