### ISSUE TITLE
Marketpay use old version and getting authentication error using createAccountHolder

### ISSUE THREAD

**Issue by sapthab** [Adyen/adyen-ruby-api-library#76]
**Describe the bug**
As per the documentation(https://docs.adyen.com/api-explorer/#/Account/v6/post/createAccountHolder), version for the API is 6. But the gem use version 4.

Even if I bump the version to 6, I get authentication error. API key has all the roles enabled. Please check

**How to reproduce**
#<Faraday::Connection:0x00007fa9ec831998 @parallel_manager=nil, @headers={"Content-Type"=>"application/json", "User-Agent"=>"adyen-ruby-api-library/4.3.0", "x-api-key"=>"AQEvhmfxJ4zLaBFKw0m/n3Q5qf3VaYxEAZZ5V2NC6nmpjaPf/ptZ++Q2ruZ5dh9VszYQwV1bDb7kfNy1WIxIIkxgBw==-xRHZ+iKxeb09WVf0HJcaXvu/UFGTwMSRLhpnDXF6QdE=-;n8xR<^SB9U,:Uaa"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x00007fa9ec831718 @handlers=[Faraday::Adapter::NetHttp]>, @url_prefix=#<URI::HTTPS https://cal-test.adyen.com/cal/services/Account/v6/createAccountHolder>, @proxy=nil>

Adyen::AuthenticationError: Adyen::AuthenticationError code:401, msg:Invalid API authentication; https://docs.adyen.com/user-management/how-to-get-the-api-key, request:{"accountHolderCode":"RBR1","accountHolderDetails":{"email":"tim@gre1en.com","individualDetails":{"name":{"firstName":"Tim","gender":"MALE","lastName":"Green"}}},"legalEntity":"Individual"}

**Comment by crrood** [comment]
Hi Sapthab,

The Github repo is meant to report bugs and suggest changes to the code.  For general support queries, please reach out to support@adyen.com.

Cheers,
Colin
