### ISSUE TITLE
Apple Pay Issue

### ISSUE THREAD

**Issue by sivasathees** [Adyen/adyen-ruby-api-library#81]
Hi,,

we have an issue related to Apple Pay. We are using several payment methods but only Apple Pay is giving us the following error:  errorCode"=>"5_002", "message"=>"Invalid Apple Pay Token", "errorType"=>"validation.

We are using the same request structure for Google Pay and it's working as expected. Please take a look at the requests and responses for both Apple Pay and Google Pay below and let me know if you see any obvious error.

 - ruby Version: 2.6.2
 - Library Version: 50

**Apple Pay:**

**Request**:

{:amount=>{:currency=>"NOK", :value=>8100}, :reference=>"cart name: C-0133 - sharma.arun1889@gmail.com", :paymentMethod=><ActionController::Parameters {"applePayCardNetwork"=>"MasterCard", "applePayToken"=>"{"version":"EC_v1","data":"1X5mCH0M8W21MOCVByb3Oqshz4ifX9p2oBmbk0BfBjyVU7iPt1bD2MHWS7sOelvqxKG1N2p5dd9z/K17KXBXMm8fg8Kn1gzt9TLu6NrUIbsu4N93a+uFth1KjpnsTVr0p/PFOpn7/mpD2EBvXtyjLFwsIZKLuRyqQq23gOFRwkAQVhJhM+OXagNIOtkxBnZ7FW1oPJE0spWFD0hF/7OCB729WAkj8XslmAd9iBLZ1ToQ39lJ3OrajCFZCblTK6Ntpm9dZ1yozZaO6cD/yNIPOOZvUOT6p7iUUt87uDh1KLQ4lLGraBrl0y0hYARt2sS+pBKh2TBzbIGBsm8x4i1tYyxLRqFeEC8BvVWoADebvgT0bEb0SVUd0vtwFCIZNJdKNAiJlpr6aVc5IO331w==","signature":"MIAGCSqGSIb3DQEHAqCAMIACAQExDzANBglghkgBZQMEAgEFADCABgkqhkiG9w0BBwEAAKCAMIID5jCCA4ugAwIBAgIIaGD2mdnMpw8wCgYIKoZIzj0EAwIwejEuMCwGA1UEAwwlQXBwbGUgQXBwbGljYXRpb24gSW50ZWdyYXRpb24gQ0EgLSBHMzEmMCQGA1UECwwdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTMB4XDTE2MDYwMzE4MTY0MFoXDTIxMDYwMjE4MTY0MFowYjEoMCYGA1UEAwwfZWNjLXNtcC1icm9rZXItc2lnbl9VQzQtU0FOREJPWDEUMBIGA1UECwwLaU9TIFN5c3RlbXMxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEgjD9q8Oc914gLFDZm0US5jfiqQHdbLPgsc1LUmeY+M9OvegaJajCHkwz3c6OKpbC9q+hkwNFxOh6RCbOlRsSlaOCAhEwggINMEUGCCsGAQUFBwEBBDkwNzA1BggrBgEFBQcwAYYpaHR0cDovL29jc3AuYXBwbGUuY29tL29jc3AwNC1hcHBsZWFpY2EzMDIwHQYDVR0OBBYEFAIkMAua7u1GMZekplopnkJxghxFMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUI/JJxE+T5O8n5sT2KGw/orv9LkswggEdBgNVHSAEggEUMIIBEDCCAQwGCSqGSIb3Y2QFATCB/jCBwwYIKwYBBQUHAgIwgbYMgbNSZWxpYW5jZSBvbiB0aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVzIGFjY2VwdGFuY2Ugb2YgdGhlIHRoZW4gYXBwbGljYWJsZSBzdGFuZGFyZCB0ZXJtcyBhbmQgY29uZGl0aW9ucyBvZiB1c2UsIGNlcnRpZmljYXRlIHBvbGljeSBhbmQgY2VydGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRzLjA2BggrBgEFBQcCARYqaHR0cDovL3d3dy5hcHBsZS5jb20vY2VydGlmaWNhdGVhdXRob3JpdHkvMDQGA1UdHwQtMCswKaAnoCWGI2h0dHA6Ly9jcmwuYXBwbGUuY29tL2FwcGxlYWljYTMuY3JsMA4GA1UdDwEB/wQEAwIHgDAPBgkqhkiG92NkBh0EAgUAMAoGCCqGSM49BAMCA0kAMEYCIQDaHGOui+X2T44R6GVpN7m2nEcr6T6sMjOhZ5NuSo1egwIhAL1a+/hp88DKJ0sv3eT3FxWcs71xmbLKD/QJ3mWagrJNMIIC7jCCAnWgAwIBAgIISW0vvzqY2pcwCgYIKoZIzj0EAwIwZzEbMBkGA1UEAwwSQXBwbGUgUm9vdCBDQSAtIEczMSYwJAYDVQQLDB1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwHhcNMTQwNTA2MjM0NjMwWhcNMjkwNTA2MjM0NjMwWjB6MS4wLAYDVQQDDCVBcHBsZSBBcHBsaWNhdGlvbiBJbnRlZ3JhdGlvbiBDQSAtIEczMSYwJAYDVQQLDB1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATwFxGEGddkhdUaXiWBB3bogKLv3nuuTeCN/EuT4TNW1WZbNa4i0Jd2DSJOe7oI/XYXzojLdrtmcL7I6CmE/1RFo4H3MIH0MEYGCCsGAQUFBwEBBDowODA2BggrBgEFBQcwAYYqaHR0cDovL29jc3AuYXBwbGUuY29tL29jc3AwNC1hcHBsZXJvb3RjYWczMB0GA1UdDgQWBBQj8knET5Pk7yfmxPYobD+iu/0uSzAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFLuw3qFYM4iapIqZ3r6966/ayySrMDcGA1UdHwQwMC4wLKAqoCiGJmh0dHA6Ly9jcmwuYXBwbGUuY29tL2FwcGxlcm9vdGNhZzMuY3JsMA4GA1UdDwEB/wQEAwIBBjAQBgoqhkiG92NkBgIOBAIFADAKBggqhkjOPQQDAgNnADBkAjA6z3KDURaZsYb7NcNWymK/9Bft2Q91TaKOvvGcgV5Ct4n4mPebWZ+Y1UENj53pwv4CMDIt1UQhsKMFd2xd8zg7kGf9F3wsIW2WT8ZyaYISb1T4en0bmcubCYkhYQaZDwmSHQAAMYIBizCCAYcCAQEwgYYwejEuMCwGA1UEAwwlQXBwbGUgQXBwbGljYXRpb24gSW50ZWdyYXRpb24gQ0EgLSBHMzEmMCQGA1UECwwdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTAghoYPaZ2cynDzANBglghkgBZQMEAgEFAKCBlTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0yMTAzMjMxMjUxMTdaMCoGCSqGSIb3DQEJNDEdMBswDQYJYIZIAWUDBAIBBQChCgYIKoZIzj0EAwIwLwYJKoZIhvcNAQkEMSIEIEVEuHwhsWe5uIwsKW5gVQI0Xhyf0M6/lrBz8PI4giL1MAoGCCqGSM49BAMCBEYwRAIgB22BvYA0nqs5LyDW73l8MSsGakrg67c7VCJRQ4vYkEcCIFK5OwvJybjf/HjjX2SfoBHJOatqCOzVPOvTTD9OfCWEAAAAAAAA","header":{"ephemeralPublicKey":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5KCOrlXReZL8imQVIFtW/PiXJUxx8lssrNyloAiTiYBi5LVUqk81mhwgDVxNTqHDeuyhiqycy3k3C7WxZz0x3w==","publicKeyHash":"DJerlvkSPFYRVcmrQoTJ2o/B89bBfcoOgBIwZw0sWTo=","transactionId":"ea9438d447217155a1acaa8107d2504229972c7a935d0662aa90981bb131cc0a"}}", "type"=>"applepay"} permitted: false>, :returnUrl=>"broadkaztapp://", :shopperEmail=>"sharma.arun1889@gmail.com", :merchantAccount=>"BroadkaztTechnologyECOM", "additionalData"=>{:allow3DS2=>true}, "channel"=>"iOS"}

**Response**:

<Adyen::AdyenResult:0x0000559e95c78c90 @response={"status"=>422, "errorCode"=>"5_002", "message"=>"Invalid Apple Pay Token", "errorType"=>"validation"}, @header={"date"=>"Tue, 23 Mar 2021 12:56:57 GMT", "server"=>"Apache", "set-cookie"=>"JSESSIONID=CF55AB152D2107FC769069F28863A39F.test8e; Path=/checkout; Secure; HttpOnly", "pspreference"=>"861616504217222C", "transfer-encoding"=>"chunked", "content-type"=>"application/json;charset=UTF-8"}, @status=422>

**Google Pay:**

**Request:**

{:amount=>{:currency=>"NOK", :value=>22900}, :reference=>"cart name: - sivasathees@gmail.com", :paymentMethod=><ActionController::Parameters {"type"=>"paywithgoogle", "googlePayToken"=>"{"signature":"MEUCIQD4D+eri2UEohnpqfvAdlrqFLzm1n8yRgjxDugiK6XBAAIgCJMLxqwq40Br8vpgyN3+AR/QooQOULtXYh5ph0A63kY\u003d","protocolVersion":"ECv1","signedMessage":"{\"encryptedMessage\":\"dZVnIwT6ymAhSZbACz7a4dW3U9ENSvVo7086VjMsXZyFJIha8fRaiFH8kzwRZEPPQv2i0tnziih69jCStl1n26b2wFIw9MHmSZhQp694QfO/bHry18r1pfkwdXURj5vjaJKPBO+7JGatp8NFJthbJTThdpk9IACocX9pZ33iCbLw/NjNtWbr3SFggc7U0zcUb6CDl4mrED4gft+qaEg2eXwsU7AQStQUVmSLwYge+/Xk6d3z0oi9NEM5+cde48AHpSMToGWIUyKxKbhNQUe3lXwnYvOf94b4kFZJJRfOhq5Gdk7Lz3/u4B4AkzgNf03Cch5ECclADqxmLZ/pPpoCvnL4XvOkqQ9pcKMWgKEfrbsEMEAojahlnw0+Mj8eZbLgzvFYK10N7H6luonO22whAqgumvVUI45i5OdSz4UVnY/AHUNFI9/VOWkEU3PeH2BA99TsAA11Q+ml999lhLwQ6USaKfhVisO4jb4uP8sIYQU3BCP9QJyxBg8js+kKr5ASEJWIIN6BdS30rwJMYxsAHsSzzfrQ+H1+KrMI2y74EXFVdz8mIqcb7IUNTY1F9cwrQKg0xZR1e5BP8KY5r06q6twHGCMGRfrj+05i\",\"ephemeralPublicKey\":\"BEpHhkSW5+bV4kk7j7zRricjhbyzYNEaCr4ycjNdmMI9ZOF7C+S37E8ElvqNdtpMxqUgP8Ckzui0B1mAKcSOTSk\\u003d\",\"tag\":\"O1DpCJ9HzhaqQXJg8qPPLc4OP6s9bJUBFc0ehp3zIxM\\u003d\"}"}", "googlePayCardNetwork"=>"VISA"} permitted: false>, :returnUrl=>"adyencheckout://com.broadkazt", :shopperEmail=>"sivasathees@gmail.com", :merchantAccount=>"BroadkaztTechnologyECOM", "additionalData"=>{:allow3DS2=>true}, "channel"=>"Android"}

**Response:**

#<Adyen::AdyenResult:0x00007f0e101242e0 @response={"pspReference"=>"852616517595206J", "resultCode"=>"Authorised", "merchantReference"=>"cart name: - sivasathees@gmail.com"}, @header={"date"=>"Tue, 23 Mar 2021 16:39:55 GMT", "server"=>"Apache", "set-cookie"=>"JSESSIONID=D1BB2049ECBAF4D9F0F13F9CB77A4757.test7e; Path=/checkout; Secure; HttpOnly", "pspreference"=>"861616517595019G", "transfer-encoding"=>"chunked", "content-type"=>"application/json;charset=UTF-8"}, @status=200>

**Comment by crrood** [comment]
Hi @sivasathees,

We are already in touch internally regarding this issue, let's keep the conversation on the iOS ticket so all the information is in one place.

Best,
Colin
