### ISSUE TITLE
Rubygems version has v50 locked into code

### ISSUE THREAD

**Issue by mkcosta** [Adyen/adyen-ruby-api-library#82]
**Describe the bug**
Downloading the gem from [rubygems](https://rubygems.org/gems/adyen-ruby-api-library), the services version for `checkout` and `payments` is locked to `50`, while in codebase is respectively `65` and `64`.

**How to reproduce**
Download the gem, print services version in console:
```ruby
Adyen::Checkout::DEFAULT_VERSION => 50
Adyen::Payments::DEFAULT_VERSION => 50
```

**Expected behavior**
Expecting to get the right versions:
```ruby
Adyen::Checkout::DEFAULT_VERSION => 65
Adyen::Payments::DEFAULT_VERSION => 64
```

**Additional context**
It should be desirable to set default versions as an argument, since you have more than one version for each service.

**Comment by crrood** [comment]
Hi mkcosta,

As noted in the docs, you can change the service-level API version:
https://github.com/Adyen/adyen-ruby-api-library#change-api-version

```
adyen.checkout.version = 65
```

Best,
Colin

**Comment by mkcosta** [comment]
That's fine, 

but the rubygems.org version it's not what it's on github, which it's weird nonetheless.

Best
Mike
