### ISSUE TITLE
Add a HISTORY.md or CHANGELOG.md

### ISSUE THREAD

**Issue by taylorbrooks** [Adyen/adyen-ruby-api-library#86]
With the new v5.0.0 release, it would be helpful to know what the breaking changes were.

**Comment by crrood** [comment]
Hi Taylor,

You can view a list of PR's included in the release under the 5.0.0 PR itself:
https://github.com/Adyen/adyen-ruby-api-library/pull/85

Best,
Colin

**Comment by taylorbrooks** [comment]
Yikes! Do you think that's the best experience for devs using this library?

1. Find the tag in Github related to the release
2. Click on the PR, look at the child PRs
3. Look at the code in each of those PRs
