### ISSUE TITLE
Checkout service modifications

### ISSUE THREAD

**Issue by mkcosta** [Adyen/adyen-ruby-api-library#91]
**ruby version**: 2.6.6
**Library version**: 5.1.0

**Is your feature request related to a problem? Please describe.**
I want to use the `Checkout` service to modify payments, such as `captures`, `cancels` and `refunds` actions:
`https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments/{paymentPspReference}/captures
`

**Describe the solution you'd like**
Calling the missing methods directly on the client, something like:
```ruby
@client.checkout.payments.captures(payload) # paymentPspReference can be discovered by payload?
```

**Describe alternatives you've considered**
We already use the `Payment` service for `capture`, `cancel` and `refund` actions, but they are not async and we cannot leverage on the webhooks.

**Comment by thesunwave** [comment]
I faced same problem here. Spent 2 days to find a way to capture authorised money via the gem.
Actually there is Payments API but it doesn't work as well (when you send `amount` API response that `amount` were not sent and returns error).

**Comment by jarednorman** [comment]
Yeah, we've worked around this, but are also facing the same issue.

**Comment by mkcosta** [comment]
> I faced same problem here. Spent 2 days to find a way to capture authorised money via the gem. Actually there is Payments API but it doesn't work as well (when you send a request object with `amount` object API response that `amount` were not sent and returns error).

If it can help, we figure out how to integrate captures, refunds and voids. You have to leverage on the `payments` API (obsolete), not the `checkout` one.

Assuming you've correctly authorised your payment, you just have to call the `payments` API with something like that:
```ruby
client = Adyen::Client.new(...)
result = client.payments.capture(merchantAccount: '<your_merchant>',
                                                        modificationAmount: { currency: '<currency_code>', value: <amount_cents_to_capture> },
                                                        originalReference: '<authorization_transaction_id>')
```

I suggest asking to Adyen support, they are quite fast answering.

Said that this is still leveraging on an old API, the `checkout` one already does this operations asynchronously, but apparently isn't supported by this client.

**Comment by thesunwave** [comment]
Thank you, @mkcosta for the offered solution. I'm just doing request by http library without gem now.

**Comment by mkcosta** [comment]
I've seen modifications are exposed since `v6.0`
